package ejudge

type Submit struct {
	SubmitId          int64  `json:"submit_id"`
	UserId            int32  `json:"user_id"`
	ContestId         int32  `json:"contest_id"`
	ProbId            int32  `json:"prob_id"`
	LangId            *int32 `json:"lang_id,omitempty"`
	Status            int32  `json:"status"`
	StatusStr         string `json:"status_str"`
	StatusDesc        string `json:"status_desc,omitempty"`
	CompilerOutput    string `json:"compiler_output,omitempty"`
	TestCheckerOutput string `json:"test_checker_output,omitempty"`
	Time              *int64 `json:"time,omitempty"`
	RealTime          *int64 `json:"real_time,omitempty"`
	ExitCode          *int32 `json:"exit_code,omitempty"`
	TermSignal        *int32 `json:"term_signal,omitempty"`
	MaxMemoryUsed     *int64 `json:"max_memory_used,omitempty"`
	MaxRss            *int64 `json:"max_rss,omitempty"`
	Input             string `json:"input,omitempty"`
	Output            string `json:"output,omitempty"`
	Error             string `json:"error,omitempty"`
	ExtUserKind       string `json:"ext_user_kind,omitempty"`
	ExtUser           string `json:"ext_user,omitempty"`
	NotifyDriver      int32  `json:"notify_driver,omitempty"`
	NotifyKind        string `json:"notify_kind,omitempty"`
	NotifyQueue       string `json:"notify_queue,omitempty"`
}

type Run struct {
	RunId            int32   `json:"run_id"`
	ContestId        int32   `json:"contest_id,omitempty"`
	RunUuid          string  `json:"run_uuid,omitempty"`
	SerialId         int64   `json:"serial_id,omitempty"`
	Status           int32   `json:"status"`
	StatusStr        string  `json:"status_str,omitempty"`
	StatusDesc       string  `json:"status_desc,omitempty"`
	RunTime          int64   `json:"run_time,omitempty"` //!!!
	Nsec             int32   `json:"nsec,omitempty"`
	RunTimeUs        int64   `json:"run_time_us,omitempty"`
	Duration         int32   `json:"duration,omitempty"`
	UserId           int32   `json:"user_id,omitempty"`
	UserLogin        string  `json:"user_login,omitempty"`
	UserName         string  `json:"user_name,omitempty"`
	ProbId           int32   `json:"prob_id,omitempty"`
	ProbName         string  `json:"prob_name,omitempty"`
	ProbInternalName string  `json:"prob_internal_name,omitempty"`
	ProbUuid         string  `json:"prob_uuid,omitempty"`
	Variant          int32   `json:"variant,omitempty"`
	RawVariant       int32   `json:"raw_variant,omitempty"`
	LangId           int32   `json:"lang_id,omitempty"`
	LangName         string  `json:"lang_name,omitempty"`
	Ip               string  `json:"ip,omitempty"`
	SslFlag          bool    `json:"ssl_flag,omitempty"`
	Ipv6Flag         bool    `json:"ipv6_flag,omitempty"`
	Sha1             string  `json:"sha1,omitempty"`
	Sha256           string  `json:"sha256,omitempty"`
	LocaleId         int32   `json:"locale_id,omitempty"`
	EolnType         int32   `json:"eoln_type,omitempty"`
	MimeType         string  `json:"mime_type,omitempty"`
	Size             int64   `json:"size,omitempty"`
	StoreFlags       int32   `json:"store_flags,omitempty"`
	IsImported       bool    `json:"is_imported,omitempty"`
	IsHidden         bool    `json:"is_hidden,omitempty"`
	IsReadonly       bool    `json:"is_readonly,omitempty"`
	PassedMode       *bool   `json:"passed_mode,omitempty"`
	Score            *int32  `json:"score,omitempty"`
	Test             *int32  `json:"test,omitempty"`
	IsMarked         bool    `json:"is_marked,omitempty"`
	ScoreAdj         int32   `json:"score_adj,omitempty"`
	JudgeId          int32   `json:"judge_id,omitempty"`
	JudgeUuid        string  `json:"judge_uuid,omitempty"`
	Pages            int32   `json:"pages,omitempty"`
	TokenFlags       int32   `json:"token_flags,omitempty"`
	TokenCount       int32   `json:"token_count,omitempty"`
	IsSaved          bool    `json:"is_saved,omitempty"`
	SavedStatus      *int32  `json:"saved_status,omitempty"`
	SavedStatusStr   string  `json:"saved_status_str,omitempty"`
	SavedScore       *int32  `json:"saved_score,omitempty"`
	SavedTest        *int32  `json:"saved_test,omitempty"`
	IsChecked        bool    `json:"is_checked,omitempty"`
	IsVcs            bool    `json:"is_vcs,omitempty"`
	VerdictBits      uint32  `json:"verdict_bits,omitempty"`
	LastChangeUs     int64   `json:"last_change_us,omitempty"`
	TestsPassed      *int32  `json:"tests_passed,omitempty"`
	RawScore         *int32  `json:"raw_score,omitempty"`
	ScoreStr         string  `json:"score_str,omitempty"`
	ExtUserKind      string  `json:"ext_user_kind,omitempty"`
	ExtUser          string  `json:"ext_user,omitempty"`
	NotifyDriver     int32   `json:"notify_driver,omitempty"`
	NotifyKind       string  `json:"notify_kind,omitempty"`
	NotifyQueue      string  `json:"notify_queue,omitempty"`
	GroupScores      []int32 `json:"groupscores,omitempty"`
}

type UserlistMember struct {
	UserID         int32  `json:"user_id,omitempty"`
	ContestID      int32  `json:"contest_id,omitempty"`
	TeamRole       int32  `json:"team_role,omitempty"`
	Serial         int32  `json:"serial,omitempty"`
	CopiedFrom     int32  `json:"copied_from,omitempty"`
	Status         int32  `json:"status,omitempty"`
	Gender         int32  `json:"gender,omitempty"`
	Grade          int32  `json:"grade,omitempty"`
	Firstname      string `json:"firstname,omitempty"`
	FirstnameEn    string `json:"firstname_en,omitempty"`
	Middlename     string `json:"middlename,omitempty"`
	MiddlenameEn   string `json:"middlename_en,omitempty"`
	Surname        string `json:"surname,omitempty"`
	SurnameEn      string `json:"surname_en,omitempty"`
	Group          string `json:"group,omitempty"`
	GroupEn        string `json:"group_en,omitempty"`
	Email          string `json:"email,omitempty"`
	Homepage       string `json:"homepage,omitempty"`
	Occupation     string `json:"occupation,omitempty"`
	OccupationEn   string `json:"occupation_en,omitempty"`
	Discipline     string `json:"discipline,omitempty"`
	Inst           string `json:"inst,omitempty"`
	InstEn         string `json:"inst_en,omitempty"`
	Instshort      string `json:"instshort,omitempty"`
	InstshortEn    string `json:"instshort_en,omitempty"`
	Fac            string `json:"fac,omitempty"`
	FacEn          string `json:"fac_en,omitempty"`
	Facshort       string `json:"facshort,omitempty"`
	FacshortEn     string `json:"facshort_en,omitempty"`
	Phone          string `json:"phone,omitempty"`
	BirthDate      int64  `json:"birth_date,omitempty"`
	EntryDate      int64  `json:"entry_date,omitempty"`
	GraduationDate int64  `json:"graduation_date,omitempty"`
	CreateTime     int64  `json:"create_time,omitempty"`
	LastChangeTime int64  `json:"last_change_time,omitempty"`
	LastAccessTime int64  `json:"last_access_time,omitempty"`
}

type UserlistUserInfo struct {
	UserID            int32            `json:"user_id,omitempty"`
	ContestID         int32            `json:"contest_id,omitempty"`
	CntsReadOnly      bool             `json:"cnts_read_only,omitempty"`
	UserName          string           `json:"user_name,omitempty"`
	Instnum           int32            `json:"instnum,omitempty"`
	TeamPasswdMethod  int              `json:"team_passwd_method,omitempty"`
	Inst              string           `json:"inst,omitempty"`
	InstEn            string           `json:"inst_en,omitempty"`
	Instshort         string           `json:"instshort,omitempty"`
	InstshortEn       string           `json:"instshort_en,omitempty"`
	Fac               string           `json:"fac,omitempty"`
	FacEn             string           `json:"fac_en,omitempty"`
	Facshort          string           `json:"facshort,omitempty"`
	FacshortEn        string           `json:"facshort_en,omitempty"`
	Homepage          string           `json:"homepage,omitempty"`
	City              string           `json:"city,omitempty"`
	CityEn            string           `json:"city_en,omitempty"`
	Country           string           `json:"country,omitempty"`
	CountryEn         string           `json:"country_en,omitempty"`
	Region            string           `json:"region,omitempty"`
	Area              string           `json:"area,omitempty"`
	Zip               string           `json:"zip,omitempty"`
	Street            string           `json:"street,omitempty"`
	Location          string           `json:"location,omitempty"`
	Spelling          string           `json:"spelling,omitempty"`
	PrinterName       string           `json:"printer_name,omitempty"`
	ExamID            string           `json:"exam_id,omitempty"`
	ExamCypher        string           `json:"exam_cypher,omitempty"`
	Languages         string           `json:"languages,omitempty"`
	Phone             string           `json:"phone,omitempty"`
	Field0            string           `json:"field0,omitempty"`
	Field1            string           `json:"field1,omitempty"`
	Field2            string           `json:"field2,omitempty"`
	Field3            string           `json:"field3,omitempty"`
	Field4            string           `json:"field4,omitempty"`
	Field5            string           `json:"field5,omitempty"`
	Field6            string           `json:"field6,omitempty"`
	Field7            string           `json:"field7,omitempty"`
	Field8            string           `json:"field8,omitempty"`
	Field9            string           `json:"field9,omitempty"`
	AvatarStore       string           `json:"avatar_store,omitempty"`
	AvatarID          string           `json:"avatar_id,omitempty"`
	AvatarSuffix      string           `json:"avatar_suffix,omitempty"`
	CreateTime        int64            `json:"create_time,omitempty"`
	LastLoginTime     int64            `json:"last_login_time,omitempty"`
	LastChangeTime    int64            `json:"last_change_time,omitempty"`
	LastAccessTime    int64            `json:"last_access_time,omitempty"`
	LastPwdchangeTime int64            `json:"last_pwdchange_time,omitempty"`
	Members           []UserlistMember `json:"members,omitempty"`
}

type UserlistUserContest struct {
	UserID         int32 `json:"user_id,omitempty"`
	ContestID      int32 `json:"contest_id,omitempty"`
	Status         int32 `json:"status,omitempty"`
	CreateTime     int64 `json:"create_time,omitempty"`
	LastChangeTime int64 `json:"last_change_time,omitempty"`
	IsInvisible    bool  `json:"is_invisible,omitempty"`
	IsBanned       bool  `json:"is_banned,omitempty"`
	IsLocked       bool  `json:"is_locked,omitempty"`
	IsIncomplete   bool  `json:"is_incomplete,omitempty"`
	IsDisqualified bool  `json:"is_disqualified,omitempty"`
	IsPrivileged   bool  `json:"is_privileged,omitempty"`
	IsRegReadonly  bool  `json:"is_reg_readonly,omitempty"`
}

type UserlistCookie struct {
	IP          string `json:"ip,omitempty"`
	Cookie      string `json:"cookie,omitempty"`
	ClientKey   string `json:"client_key,omitempty"`
	Expire      int64  `json:"expire,omitempty"`
	UserID      int32  `json:"user_id,omitempty"`
	IsSSL       bool   `json:"ssl,omitempty"`
	ContestID   int32  `json:"contest_id,omitempty"`
	LocaleID    int32  `json:"locale_id,omitempty"`
	PrivLevel   int32  `json:"priv_level,omitempty"`
	Role        int32  `json:"role,omitempty"`
	IsRecovery  bool   `json:"recovery,omitempty"`
	IsTeamLogin bool   `json:"team_login,omitempty"`
	IsWS        bool   `json:"is_ws,omitempty"`
	IsJob       bool   `json:"is_job,omitempty"`
}

type UserlistUser struct {
	UserID              int32                 `json:"user_id,omitempty"`
	IsPrivileged        bool                  `json:"is_privileged,omitempty"`
	IsInvisible         bool                  `json:"is_invisible,omitempty"`
	IsBanned            bool                  `json:"is_banned,omitempty"`
	IsLocked            bool                  `json:"is_locked,omitempty"`
	ShowLogin           bool                  `json:"show_login,omitempty"`
	ShowEmail           bool                  `json:"show_email,omitempty"`
	ReadOnly            bool                  `json:"read_only,omitempty"`
	NeverClean          bool                  `json:"never_clean,omitempty"`
	SimpleRegistration  bool                  `json:"simple_registration,omitempty"`
	UserLogin           string                `json:"user_login"`
	Email               string                `json:"email,omitempty"`
	PasswdMethod        int                   `json:"passwd_method,omitempty"`
	Extra1              string                `json:"extra1,omitempty"`
	RegistrationTime    int64                 `json:"registration_time,omitempty"`
	LastLoginTime       int64                 `json:"last_login_time,omitempty"`
	LastMinorChangeTime int64                 `json:"last_minor_change_time,omitempty"`
	LastChangeTime      int64                 `json:"last_change_time,omitempty"`
	LastAccessTime      int64                 `json:"last_access_time,omitempty"`
	LastPwdchangeTime   int64                 `json:"last_pwdchange_time,omitempty"`
	Infos               []UserlistUserInfo    `json:"infos,omitempty"`
	Contests            []UserlistUserContest `json:"contests,omitempty"`
	Cookies             []UserlistCookie      `json:"cookies,omitempty"`
}

type Global struct {
	SleepTime                   int32    `json:"sleep_time,omitempty"`
	ServeSleepTime              int32    `json:"serve_sleep_time,omitempty"`
	ContestTime                 int32    `json:"contest_time,omitempty"`
	MaxRunSize                  int32    `json:"max_run_size,omitempty"`
	MaxRunTotal                 int32    `json:"max_run_total,omitempty"`
	MaxRunNum                   int32    `json:"max_run_num,omitempty"`
	MaxClarSize                 int32    `json:"max_clar_size,omitempty"`
	MaxClarTotal                int32    `json:"max_clar_total,omitempty"`
	MaxClarNum                  int32    `json:"max_clar_num,omitempty"`
	BoardFogTime                int32    `json:"board_fog_time,omitempty"`
	BoardUnfogTime              int32    `json:"board_unfog_time,omitempty"`
	AutoupdateStandings         bool     `json:"autoupdate_standings,omitempty"`
	UseAcNotOk                  bool     `json:"use_ac_not_ok,omitempty"`
	InactivityTimeout           int32    `json:"inactivity_timeout,omitempty"`
	DisableAutoTesting          bool     `json:"disable_auto_testing,omitempty"`
	DisableTesting              bool     `json:"disable_testing,omitempty"`
	EnableRunlogMerge           bool     `json:"enable_runlog_merge,omitempty"`
	SecureRun                   bool     `json:"secure_run,omitempty"`
	DetectViolations            bool     `json:"detect_violations,omitempty"`
	EnableMemoryLimitError      bool     `json:"enable_memory_limit_error,omitempty"`
	AdvancedLayout              bool     `json:"advanced_layout,omitempty"`
	UuidRunStore                bool     `json:"uuid_run_store,omitempty"`
	DisableBsonStore            bool     `json:"disable_bson_store,omitempty"`
	Enable32bitCheckers         bool     `json:"enable_32bit_checkers,omitempty"`
	IgnoreBom                   bool     `json:"ignore_bom,omitempty"`
	DisableUserDatabase         bool     `json:"disable_user_database,omitempty"`
	EnableMaxStackSize          bool     `json:"enable_max_stack_size,omitempty"`
	TimeLimitRetryCount         int32    `json:"time_limit_retry_count,omitempty"`
	ScoreNBestProblems          int32    `json:"score_n_best_problems,omitempty"`
	RequireProblemUuid          bool     `json:"require_problem_uuid,omitempty"`
	StandIgnoreAfter            int64    `json:"stand_ignore_after,omitempty"`
	ContestFinishTime           int64    `json:"contest_finish_time,omitempty"`
	AppealDeadline              int64    `json:"appeal_deadline,omitempty"`
	TeamEnableSrcView           bool     `json:"team_enable_src_view,omitempty"`
	TeamEnableRepView           bool     `json:"team_enable_rep_view,omitempty"`
	TeamEnableCeView            bool     `json:"team_enable_ce_view,omitempty"`
	TeamShowJudgeReport         bool     `json:"team_show_judge_report,omitempty"`
	DisableClars                bool     `json:"disable_clars,omitempty"`
	DisableTeamClars            bool     `json:"disable_team_clars,omitempty"`
	DisableSubmitAfterOk        bool     `json:"disable_submit_after_ok,omitempty"`
	IgnoreCompileErrors         bool     `json:"ignore_compile_errors,omitempty"`
	EnableContinue              bool     `json:"enable_continue,omitempty"`
	EnableReportUpload          bool     `json:"enable_report_upload,omitempty"`
	PriorityAdjustment          int32    `json:"priority_adjustment,omitempty"`
	IgnoreSuccessTime           bool     `json:"ignore_success_time,omitempty"`
	DisableFailedTestView       bool     `json:"disable_failed_test_view,omitempty"`
	AlwaysShowProblems          bool     `json:"always_show_problems,omitempty"`
	DisableUserStandings        bool     `json:"disable_user_standings,omitempty"`
	DisableLanguage             bool     `json:"disable_language,omitempty"`
	ProblemNavigation           bool     `json:"problem_navigation,omitempty"`
	ProblemTabSize              int32    `json:"problem_tab_size,omitempty"`
	VerticalNavigation          bool     `json:"vertical_navigation,omitempty"`
	DisableVirtualStart         bool     `json:"disable_virtual_start,omitempty"`
	DisableVirtualAutoJudge     bool     `json:"disable_virtual_auto_judge,omitempty"`
	EnableAutoPrintProtocol     bool     `json:"enable_auto_print_protocol,omitempty"`
	NotifyClarReply             bool     `json:"notify_clar_reply,omitempty"`
	NotifyStatusChange          bool     `json:"notify_status_change,omitempty"`
	MemoizeUserResults          bool     `json:"memoize_user_results,omitempty"`
	DisableAutoRefresh          bool     `json:"disable_auto_refresh,omitempty"`
	EnableEolnSelect            bool     `json:"enable_eoln_select,omitempty"`
	StartOnFirstLogin           bool     `json:"start_on_first_login,omitempty"`
	EnableVirtualRestart        bool     `json:"enable_virtual_restart,omitempty"`
	PreserveLineNumbers         bool     `json:"preserve_line_numbers,omitempty"`
	EnableRemoteCache           bool     `json:"enable_remote_cache,omitempty"`
	EnableRunProps              bool     `json:"enable_run_props,omitempty"`
	EnableL10n                  bool     `json:"enable_l10n,omitempty"`
	L10nDir                     string   `json:"l10n_dir,omitempty"`
	StandingsLocale             string   `json:"standings_locale,omitempty"`
	CheckerLocale               string   `json:"checker_locale,omitempty"`
	ContestId                   int32    `json:"contest_id,omitempty"`
	SocketPath                  string   `json:"socket_path,omitempty"`
	ContestsDir                 string   `json:"contests_dir,omitempty"`
	LangConfigDir               string   `json:"lang_config_dir,omitempty"`
	Charset                     string   `json:"charset,omitempty"`
	StandingsCharset            string   `json:"standings_charset,omitempty"`
	Stand2Charset               string   `json:"stand2_charset,omitempty"`
	PlogCharset                 string   `json:"plog_charset,omitempty"`
	ConfDir                     string   `json:"conf_dir,omitempty"`
	ProblemsDir                 string   `json:"problems_dir,omitempty"`
	ScriptDir                   string   `json:"script_dir,omitempty"`
	TestDir                     string   `json:"test_dir,omitempty"`
	CorrDir                     string   `json:"corr_dir,omitempty"`
	InfoDir                     string   `json:"info_dir,omitempty"`
	TgzDir                      string   `json:"tgz_dir,omitempty"`
	CheckerDir                  string   `json:"checker_dir,omitempty"`
	StatementDir                string   `json:"statement_dir,omitempty"`
	PluginDir                   string   `json:"plugin_dir,omitempty"`
	TestSfx                     string   `json:"test_sfx,omitempty"`
	CorrSfx                     string   `json:"corr_sfx,omitempty"`
	InfoSfx                     string   `json:"info_sfx,omitempty"`
	TgzSfx                      string   `json:"tgz_sfx,omitempty"`
	TgzdirSfx                   string   `json:"tgzdir_sfx,omitempty"`
	EjudgeCheckersDir           string   `json:"ejudge_checkers_dir,omitempty"`
	ContestStartCmd             string   `json:"contest_start_cmd,omitempty"`
	ContestStopCmd              string   `json:"contest_stop_cmd,omitempty"`
	DescriptionFile             string   `json:"description_file,omitempty"`
	ContestPluginFile           string   `json:"contest_plugin_file,omitempty"`
	VirtualEndOptions           string   `json:"virtual_end_options,omitempty"`
	SuperRunDir                 string   `json:"super_run_dir,omitempty"`
	CompileServerId             string   `json:"compile_server_id,omitempty"`
	TestPat                     string   `json:"test_pat,omitempty"`
	CorrPat                     string   `json:"corr_pat,omitempty"`
	InfoPat                     string   `json:"info_pat,omitempty"`
	TgzPat                      string   `json:"tgz_pat,omitempty"`
	TgzdirPat                   string   `json:"tgzdir_pat,omitempty"`
	ClardbPlugin                string   `json:"clardb_plugin,omitempty"`
	RundbPlugin                 string   `json:"rundb_plugin,omitempty"`
	XuserPlugin                 string   `json:"xuser_plugin,omitempty"`
	StatusPlugin                string   `json:"status_plugin,omitempty"`
	VariantPlugin               string   `json:"variant_plugin,omitempty"`
	VarDir                      string   `json:"var_dir,omitempty"`
	RunLogFile                  string   `json:"run_log_file,omitempty"`
	ClarLogFile                 string   `json:"clar_log_file,omitempty"`
	ArchiveDir                  string   `json:"archive_dir,omitempty"`
	ClarArchiveDir              string   `json:"clar_archive_dir,omitempty"`
	RunArchiveDir               string   `json:"run_archive_dir,omitempty"`
	ReportArchiveDir            string   `json:"report_archive_dir,omitempty"`
	TeamReportArchiveDir        string   `json:"team_report_archive_dir,omitempty"`
	XmlReportArchiveDir         string   `json:"xml_report_archive_dir,omitempty"`
	FullArchiveDir              string   `json:"full_archive_dir,omitempty"`
	AuditLogDir                 string   `json:"audit_log_dir,omitempty"`
	UuidArchiveDir              string   `json:"uuid_archive_dir,omitempty"`
	TeamExtraDir                string   `json:"team_extra_dir,omitempty"`
	LegacyStatusDir             string   `json:"legacy_status_dir,omitempty"`
	WorkDir                     string   `json:"work_dir,omitempty"`
	PrintWorkDir                string   `json:"print_work_dir,omitempty"`
	DiffWorkDir                 string   `json:"diff_work_dir,omitempty"`
	A2psPath                    string   `json:"a2ps_path,omitempty"`
	A2psArgs                    []string `json:"a2ps_args,omitempty"`
	LprPath                     string   `json:"lpr_path,omitempty"`
	LprArgs                     []string `json:"lpr_args,omitempty"`
	DiffPath                    string   `json:"diff_path,omitempty"`
	CompileDir                  string   `json:"compile_dir,omitempty"`
	CompileQueueDir             string   `json:"compile_queue_dir,omitempty"`
	CompileSrcDir               string   `json:"compile_src_dir,omitempty"`
	ExtraCompileDirs            []string `json:"extra_compile_dirs,omitempty"`
	CompileOutDir               string   `json:"compile_out_dir,omitempty"`
	CompileStatusDir            string   `json:"compile_status_dir,omitempty"`
	CompileReportDir            string   `json:"compile_report_dir,omitempty"`
	CompileWorkDir              string   `json:"compile_work_dir,omitempty"`
	RunDir                      string   `json:"run_dir,omitempty"`
	RunQeuueDir                 string   `json:"run_queue_dir,omitempty"`
	RunExeDir                   string   `json:"run_exe_dir,omitempty"`
	RunOutDir                   string   `json:"run_out_dir,omitempty"`
	RunStatusDir                string   `json:"run_status_dir,omitempty"`
	RunReportDir                string   `json:"run_report_dir,omitempty"`
	RunTeamReportDir            string   `json:"run_team_report_dir,omitempty"`
	RunFullArchiveDir           string   `json:"run_full_archive_dir,omitempty"`
	RunWorkDir                  string   `json:"run_work_dir,omitempty"`
	RunCheckDir                 string   `json:"run_check_dir,omitempty"`
	HtdocsDir                   string   `json:"htdocs_dir,omitempty"`
	ScoreSystem                 string   `json:"score_system,omitempty"`
	TestsToAccept               int32    `json:"tests_to_accept,omitempty"`
	IsVirtual                   bool     `json:"is_virtual,omitempty"`
	PruneEmptyUsers             bool     `json:"prune_empty_users,omitempty"`
	RoundingMode                string   `json:"rounding_mode,omitempty"`
	MaxFileLength               int32    `json:"max_file_length,omitempty"`
	MaxLineLength               int32    `json:"max_line_length,omitempty"`
	MaxCmdLength                int32    `json:"max_cmd_length,omitempty"`
	TeamInfoUrl                 string   `json:"team_info_url,omitempty"`
	ProbInfoUrl                 string   `json:"prob_info_url,omitempty"`
	StandingsFileName           string   `json:"standings_file_name,omitempty"`
	StandHeaderFile             string   `json:"stand_header_file,omitempty"`
	StandFooterFile             string   `json:"stand_footer_file,omitempty"`
	StandSymlinkDir             string   `json:"stand_symlink_dir,omitempty"`
	UsersOnPage                 int32    `json:"users_on_page,omitempty"`
	StandFileName2              string   `json:"stand_file_name_2,omitempty"`
	StandFancyStyle             bool     `json:"stand_fancy_style,omitempty"`
	StandExtraFormat            string   `json:"stand_extra_format,omitempty"`
	StandExtraLegend            string   `json:"stand_extra_legend,omitempty"`
	StandExtraAttr              string   `json:"stand_extra_attr,omitempty"`
	StandTableAttr              string   `json:"stand_table_attr,omitempty"`
	StandPlaceAttr              string   `json:"stand_place_attr,omitempty"`
	StandTeamAttr               string   `json:"stand_team_attr,omitempty"`
	StandProbAttr               string   `json:"stand_prob_attr,omitempty"`
	StandSolvedAttr             string   `json:"stand_solved_attr,omitempty"`
	StandScoreAttr              string   `json:"stand_score_attr,omitempty"`
	StandPenaltyAttr            string   `json:"stand_penalty_attr,omitempty"`
	StandTimeAttr               string   `json:"stand_time_attr,omitempty"`
	StandSelfRowAttr            string   `json:"stand_self_row_attr,omitempty"`
	StandRRowAttr               string   `json:"stand_r_row_attr,omitempty"`
	StandVRowAttr               string   `json:"stand_v_row_attr,omitempty"`
	StandURowAttr               string   `json:"stand_u_row_attr,omitempty"`
	StandSuccessAttr            string   `json:"stand_success_attr,omitempty"`
	StandFailAttr               string   `json:"stand_fail_attr,omitempty"`
	StandTransAttr              string   `json:"stand_trans_attr,omitempty"`
	StandDisqAttr               string   `json:"stand_disq_attr,omitempty"`
	StandUseLogin               bool     `json:"stand_use_login,omitempty"`
	StandShowAvatar             bool     `json:"stand_show_avatar,omitempty"`
	StandShowFirstSolver        bool     `json:"stand_show_first_solver,omitempty"`
	StandShowOkTime             bool     `json:"stand_show_ok_time,omitempty"`
	StandShowAttNum             bool     `json:"stand_show_att_num,omitempty"`
	StandSortBySolved           bool     `json:"stand_sort_by_solved,omitempty"`
	StandRowAttr                []string `json:"stand_row_attr,omitempty"`
	StandPageTableAttr          string   `json:"stand_page_table_attr,omitempty"`
	StandPageRowAttr            []string `json:"stand_page_row_attr,omitempty"`
	StandPageColAttr            []string `json:"stand_page_col_attr,omitempty"`
	StagePageCurAttr            string   `json:"stand_page_cur_attr,omitempty"`
	StandCollateName            bool     `json:"stand_collate_name,omitempty"`
	StandEnablePenalty          bool     `json:"stand_enable_penalty,omitempty"`
	Stand2FileNAme              string   `json:"stand2_file_name,omitempty"`
	Stand2HeaderFile            string   `json:"stand2_header_file,omitempty"`
	Stand2FooterFile            string   `json:"stand2_footer_file,omitempty"`
	Stand2SymlinkDir            string   `json:"stand2_symlink_dir,omitempty"`
	PlogFileName                string   `json:"plog_file_name,omitempty"`
	PlogHeaderFile              string   `json:"plog_header_file,omitempty"`
	PlogFooterFile              string   `json:"plog_footer_file,omitempty"`
	PlogUpdateTime              int32    `json:"plog_update_time,omitempty"`
	PlogSymlinkDir              string   `json:"plog_symlink_dir,omitempty"`
	InternalXmlUpdateTime       int32    `json:"internal_xml_update_time,omitempty"`
	ExternalXmlUpdateTime       int32    `json:"external_xml_update_time,omitempty"`
	UserExamProtocolHeaderFile  string   `json:"user_exam_protocol_header_file,omitempty"`
	UserExampProtocolFooterFile string   `json:"user_exam_protocol_footer_file,omitempty"`
	ProbExamProtocolHeaderFile  string   `json:"prob_exam_protocol_header_file,omitempty"`
	ProbExamProtocolFooterFile  string   `json:"prob_exam_protocol_footer_file,omitempty"`
	FullExamProtocolHeaderFile  string   `json:"full_exam_protocol_header_file,omitempty"`
	FullExamProtocolFooterFile  string   `json:"full_exam_protocol_footer_file,omitempty"`
	ExtendedSound               bool     `json:"extended_sound,omitempty"`
	DisableSound                bool     `json:"disable_sound,omitempty"`
	SoundPlayer                 string   `json:"sound_player,omitempty"`
	AcceptSound                 string   `json:"accept_sound,omitempty"`
	RuntimeSound                string   `json:"runtime_sound,omitempty"`
	TimelimitSound              string   `json:"timelimit_sound,omitempty"`
	PresentationSound           string   `json:"presentation_sound,omitempty"`
	WrongSound                  string   `json:"wrong_sound,omitempty"`
	InternalSound               string   `json:"internal_sound,omitempty"`
	StartSound                  string   `json:"start_sound,omitempty"`
	TeamDownloadTime            int32    `json:"team_download_time,omitempty"`
	CrSerializationKey          int32    `json:"cr_serialization_key,omitempty"`
	ShowAstrTime                bool     `json:"show_astr_time,omitempty"`
	IgnoreDuplicatedRuns        bool     `json:"ignore_duplicated_runs,omitempty"`
	ReportErrorCode             bool     `json:"report_error_code,omitempty"`
	AutoShortProblemName        bool     `json:"auto_short_problem_name,omitempty"`
	CompileRealTimeLimit        int32    `json:"compile_real_time_limit,omitempty"`
	CheckerRealTimeLimit        int32    `json:"checker_real_time_limit,omitempty"`
	ShowDeadline                bool     `json:"show_deadline,omitempty"`
	SeparateUserScore           bool     `json:"separate_user_score,omitempty"`
	ShowSha1                    bool     `json:"show_sha1,omitempty"`
	ShowJudgeIdentity           bool     `json:"show_judge_identity,omitempty"`
	UseGzip                     bool     `json:"use_gzip,omitempty"`
	MinGzipSize                 int32    `json:"min_gzip_size,omitempty"`
	UseDirHierarchy             bool     `json:"use_dir_hierarchy,omitempty"`
	HtmlReport                  bool     `json:"html_report,omitempty"`
	XmlReport                   bool     `json:"xml_report,omitempty"`
	EnableFullArchive           bool     `json:"enable_full_archive,omitempty"`
	CpuBogomips                 int32    `json:"cpu_bogomips,omitempty"`
	SkipFullTesting             bool     `json:"skip_full_testing,omitempty"`
	SkipAcceptTesting           bool     `json:"skip_accept_testing,omitempty"`
	EnableProblemHistory        bool     `json:"enable_problem_history,omitempty"`
	VariantMapFile              string   `json:"variant_map_file,omitempty"`
	EnablePrinting              bool     `json:"enable_printing,omitempty"`
	DisableBannerPage           bool     `json:"disable_banner_page,omitempty"`
	PrintoutUsesLogin           bool     `json:"printout_uses_login,omitempty"`
	TeamPageQuota               int32    `json:"team_page_quota,omitempty"`
	PrintJustCopy               bool     `json:"print_just_copy,omitempty"`
	CompileMaxVmSize            int64    `json:"compile_max_vm_size,omitempty"`
	CompileMaxStackSize         int64    `json:"compile_max_stack_size,omitempty"`
	CompileMaxFileSize          int64    `json:"compile_max_file_size,omitempty"`
	CompileMaxRssSize           int64    `json:"compile_max_rss_size,omitempty"`
	UserPriorityAdjustments     []string `json:"user_priority_adjustments,omitempty"`
	ContestantStatusNum         int32    `json:"contestant_status_num,omitempty"`
	ContestantStatusLegend      []string `json:"contestant_status_legend,omitempty"`
	ContestantStatusRowAttr     []string `json:"contestant_status_row_attr,omitempty"`
	StandShowContestantStatus   bool     `json:"stand_show_contestant_status,omitempty"`
	StandShowWarnNumber         bool     `json:"stand_show_warn_number,omitempty"`
	StandContestantStatusAttr   string   `json:"stand_contestant_status_attr,omitempty"`
	StandWarnNumberAttr         string   `json:"stand_warn_number_attr,omitempty"`
	LoadUserGroup               []string `json:"load_user_group,omitempty"`
	Tokens                      string   `json:"tokens,omitempty"`
	DatesConfigFile             string   `json:"dates_config_file,omitempty"`
	TimeBetweenSubmits          int32    `json:"time_between_submits,omitempty"`
	MaxInputSize                int32    `json:"max_input_size,omitempty"`
	MaxSubmitNum                int32    `json:"max_submit_num,omitempty"`
	MaxSubmitTotal              int32    `json:"max_submit_total,omitempty"`
	EnableLanguageImport        bool     `json:"enable_language_import,omitempty"`
	LanguageImport              []string `json:"language_import,omitempty"`
	NotificationSpec            string   `json:"notification_spec,omitempty"`
}

type Language struct {
	Id                       uint32   `json:"id"`
	CompileId                uint32   `json:"compile_id,omitempty"`
	Disabled                 bool     `json:"disabled,omitempty"`
	CompileRealTimeLimit     int64    `json:"compile_real_time_limit,omitempty"`
	Binary                   bool     `json:"binary,omitempty"`
	PriorityAdjustment       int32    `json:"priority_adjustment,omitempty"`
	Insecure                 bool     `json:"insecure,omitempty"`
	DisableSecurity          bool     `json:"disable_security,omitempty"`
	EnableSuidRun            bool     `json:"enable_suid_run,omitempty"`
	IsDos                    bool     `json:"is_dos,omitempty"`
	ShortName                string   `json:"short_name,omitempty"`
	LongName                 string   `json:"long_name,omitempty"`
	Key                      string   `json:"key,omitempty"`
	Arch                     string   `json:"arch,omitempty"`
	SrcSfx                   string   `json:"src_sfx,omitempty"`
	ExeSfx                   string   `json:"exe_sfx,omitempty"`
	ContentType              string   `json:"content_type,omitempty"`
	Cmd                      string   `json:"cmd,omitempty"`
	StyleCheckerCmd          string   `json:"style_checker_cmd,omitempty"`
	StyleCheckerEnv          []string `json:"style_checker_env,omitempty"`
	Extid                    string   `json:"extid,omitempty"`
	SuperRunDir              string   `json:"super_run_dir,omitempty"`
	DisableAutoTesting       bool     `json:"disable_auto_testing,omitempty"`
	DisableTesting           bool     `json:"disable_testing,omitempty"`
	EnableCustom             bool     `json:"enable_custom,omitempty"`
	EnableEjudgeEnv          bool     `json:"enable_ejudge_env,omitempty"`
	PreserveLineNumbers      bool     `json:"preserve_line_numbers,omitempty"`
	DefaultDisabled          bool     `json:"default_disabled,omitempty"`
	Enabled                  bool     `json:"enabled,omitempty"`
	DisableAutoUpdate        bool     `json:"disable_auto_update,omitempty"`
	EnableNetwork            bool     `json:"enable_network,omitempty"`
	EnableRemoteCache        bool     `json:"enable_remote_cache,omitempty"`
	MaxVmSize                int64    `json:"max_vm_size,omitempty"`
	MaxStackSize             int64    `json:"max_stack_size,omitempty"`
	MaxFileSize              int64    `json:"max_file_size,omitempty"`
	MaxRssSize               int64    `json:"max_rss_size,omitempty"`
	RunMaxStackSize          int64    `json:"run_max_stack_size,omitempty"`
	RunMaxVmSize             int64    `json:"run_max_vm_size,omitempty"`
	RunMaxRssSize            int64    `json:"run_max_rss_size,omitempty"`
	RunMaxFileSize           int64    `json:"run_max_file_size,omitempty"`
	CompileDirIndex          int32    `json:"compile_dir_index,omitempty"`
	CompilerEnv              []string `json:"compiler_env,omitempty"`
	CompileServerId          string   `json:"compile_server_id,omitempty"`
	MultiHeaderSuffix        string   `json:"multi_header_suffix,omitempty"`
	ContainerOptions         string   `json:"container_options,omitempty"`
	CompilerContainerOptions string   `json:"compiler_container_options,omitempty"`
	CleanUpCmd               string   `json:"clean_up_cmd,omitempty"`
	RunEnvFile               string   `json:"run_env_file,omitempty"`
	CleanUpEnvFile           string   `json:"clean_up_env_file,omitempty"`
	Version                  string   `json:"version,omitempty"`
}

type Problem struct {
	Id                           int32     `json:"id"`
	TesterId                     int32     `json:"tester_id,omitempty"`
	Type                         string    `json:"type"`
	Super                        string    `json:"super,omitempty"`
	ShortName                    string    `json:"short_name,omitempty"`
	VariantNum                   int32     `json:"variant_num,omitempty"`
	FullScore                    *int32    `json:"full_score,omitempty"`
	FullUserScore                *int32    `json:"full_user_score,omitempty"`
	MinScore1                    *int32    `json:"min_score_1,omitempty"`
	MinScore2                    *int32    `json:"min_score_2,omitempty"`
	Abstract                     bool      `json:"abstract,omitempty"`
	ManualChecking               *bool     `json:"manual_checking,omitempty"`
	CheckPresentation            *bool     `json:"check_presentation,omitempty"`
	ScoringChecker               *bool     `json:"scoring_checker,omitempty"`
	EnableCheckerToken           *bool     `json:"enable_checker_token,omitempty"`
	InteractiveValuer            *bool     `json:"interactive_valuer,omitempty"`
	DisablePe                    *bool     `json:"disable_pe,omitempty"`
	DisableWtl                   *bool     `json:"disable_wtl,omitempty"`
	WtlIsCf                      *bool     `json:"wtl_is_cf,omitempty"`
	UseStdin                     *bool     `json:"use_stdin,omitempty"`
	UseStdout                    *bool     `json:"use_stdout,omitempty"`
	CombinedStdin                *bool     `json:"combined_stdin,omitempty"`
	CombinedStdout               *bool     `json:"combined_stdout,omitempty"`
	BinaryInput                  *bool     `json:"binary_input,omitempty"`
	Binary                       *bool     `json:"binary,omitempty"`
	IgnoreExitCode               *bool     `json:"ignore_exit_code,omitempty"`
	IgnoreTermSignal             *bool     `json:"ignore_term_signal,omitempty"`
	OlympiadMode                 *bool     `json:"olympiad_mode,omitempty"`
	ScoreLatest                  *bool     `json:"score_latest,omitempty"`
	ScoreLatestOrUnmarked        *bool     `json:"score_latest_or_unmarked,omitempty"`
	ScoreLatestMarked            *bool     `json:"score_latest_marked,omitempty"`
	ScoreTokenized               *bool     `json:"score_tokenized,omitempty"`
	UseAcNotOk                   *bool     `json:"use_ac_not_ok,omitempty"`
	IgnorePrevAc                 *bool     `json:"ignore_prev_ac,omitempty"`
	TeamEnableRepView            *bool     `json:"TeamEnableRepView,omitempty"`
	TeamEnableCeView             *bool     `json:"team_enable_ce_view,omitempty"`
	TeamShowJudgeReport          *bool     `json:"team_show_judge_report,omitempty"`
	ShowCheckerComment           *bool     `json:"show_checker_comment,omitempty"`
	IgnoreCompileErrors          *bool     `json:"ignore_compile_errors,omitempty"`
	VariableFullScore            *bool     `json:"variable_full_score,omitempty"`
	IgnorePenalty                *bool     `json:"ignore_penalty,omitempty"`
	UseCorr                      *bool     `json:"use_corr,omitempty"`
	UseInfo                      *bool     `json:"use_info,omitempty"`
	UseTgz                       *bool     `json:"use_tgz,omitempty"`
	AcceptPartial                *bool     `json:"accept_partial,omitempty"`
	DisableUserSubmit            *bool     `json:"disable_user_submit,omitempty"`
	DisableTab                   *bool     `json:"disable_tab,omitempty"`
	UnrestrictedStatement        *bool     `json:"unrestricted_statement,omitempty"`
	StatementIgnoreIp            *bool     `json:"statement_ignore_ip,omitempty"`
	RestrictedStatement          *bool     `json:"restricted_statement,omitempty"`
	EnableSubmitAfterReject      *bool     `json:"enable_submit_after_reject,omitempty"`
	HideFileNames                *bool     `json:"hide_file_names,omitempty"`
	HideRealTimeLimit            *bool     `json:"hide_real_time_limit,omitempty"`
	EnableTokens                 *bool     `json:"enable_tokens,omitempty"`
	TokensForUserAc              *bool     `json:"tokens_for_user_ac,omitempty"`
	DisableSubmitAfterOk         *bool     `json:"disable_submit_after_ok,omitempty"`
	DisableAutoTesting           *bool     `json:"disable_auto_testing,omitempty"`
	DisableTesting               *bool     `json:"disable_testing,omitempty"`
	EnableCompilation            *bool     `json:"enable_compilation,omitempty"`
	SkipTesting                  *bool     `json:"skip_testing,omitempty"`
	Hidden                       *bool     `json:"hidden,omitempty"`
	StandHideTime                *bool     `json:"stand_hide_time,omitempty"`
	AdvanceToNext                *bool     `json:"advance_to_next,omitempty"`
	DisableCtrlChars             *bool     `json:"disable_ctrl_chars,omitempty"`
	EnableTextForm               *bool     `json:"enable_text_form,omitempty"`
	StandIgnoreScore             *bool     `json:"stand_ignore_score,omitempty"`
	StandLastColumn              *bool     `json:"stand_last_column,omitempty"`
	DisableSecurity              *bool     `json:"disable_security,omitempty"`
	EnableSuidRun                *bool     `json:"enable_suid_run,omitempty"`
	EnableContainer              *bool     `json:"enable_container,omitempty"`
	EnableDynamicPriority        *bool     `json:"enable_dynamic_priority,omitempty"`
	ValuerSetsMarked             *bool     `json:"valuer_sets_marked,omitempty"`
	IgnoreUnmarked               *bool     `json:"ignore_unmarked,omitempty"`
	DisableStderr                *bool     `json:"disable_stderr,omitempty"`
	EnableProcessGroup           *bool     `json:"enable_process_group,omitempty"`
	EnableKillAll                *bool     `json:"enable_kill_all,omitempty"`
	HideVariant                  *bool     `json:"hide_variant,omitempty"`
	EnableTestlibMode            *bool     `json:"enable_testlib_mode,omitempty"`
	AutoassignVariants           *bool     `json:"autoassign_variants,omitempty"`
	RequireAny                   *bool     `json:"require_any,omitempty"`
	EnableExtendedInfo           *bool     `json:"enable_extended_info,omitempty"`
	StopOnFirstFail              *bool     `json:"stop_on_first_fail,omitempty"`
	EnableControlSocket          *bool     `json:"enable_control_socket,omitempty"`
	CopyExeToTgzdir              *bool     `json:"copy_exe_to_tgzdir,omitempty"`
	EnableMultiHeader            *bool     `json:"enable_multi_header,omitempty"`
	UseLangMultiHeader           *bool     `json:"use_lang_multi_header,omitempty"`
	NotifyOnSubmit               *bool     `json:"notify_on_submit,omitempty"`
	EnableUserInput              *bool     `json:"enable_user_input,omitempty"`
	EnableVcs                    *bool     `json:"enable_vcs,omitempty"`
	EnableIframeStatement        *bool     `json:"enable_iframe_statement,omitempty"`
	EnableSrcForTesting          *bool     `json:"enable_src_for_testing,omitempty"`
	DisableVmSizeLimit           *bool     `json:"disable_vm_size_limit,omitempty"`
	EnableGroupMerge             *bool     `json:"enable_group_merge,omitempty"`
	IgnoreSigpipe                *bool     `json:"ignore_sigpipe,omitempty"`
	ExaminatorNum                *int32    `json:"examinator_num,omitempty"`
	RealTimeLimit                *int32    `json:"real_time_limit,omitempty"`
	TimeLimit                    *int32    `json:"time_limit,omitempty"`
	TimeLimitMillis              *int32    `json:"time_limit_millis,omitempty"`
	TestScore                    *int32    `json:"test_score,omitempty"`
	RunPenalty                   *int32    `json:"run_penalty,omitempty"`
	AcmRunPenalty                *int32    `json:"acm_run_penalty,omitempty"`
	DisqualifiedPenalty          *int32    `json:"disqualified_penalty,omitempty"`
	CompileErrorPenalty          *int32    `json:"compile_error_penalty,omitempty"`
	TestsToAccept                *int32    `json:"tests_to_accept,omitempty"`
	MinTestsToAccept             *int32    `json:"min_tests_to_accept,omitempty"`
	CheckerRealTimeLimit         *int32    `json:"checker_real_time_limit,omitempty"`
	CheckerTimeLimitMs           *int32    `json:"checker_time_limit_ms,omitempty"`
	PriorityAdjustment           *int32    `json:"priority_adjustment,omitempty"`
	ScoreMultiplier              *int32    `json:"score_multiplier,omitempty"`
	PrevRunsToShow               *int32    `json:"prev_runs_to_show,omitempty"`
	MaxUserRunCount              *int32    `json:"max_user_run_count,omitempty"`
	LongName                     string    `json:"long_name,omitempty"`
	StandName                    *string   `json:"stand_name,omitempty"`
	StandColumn                  *string   `json:"stand_column,omitempty"`
	GroupName                    *string   `json:"group_name,omitempty"`
	InternalName                 *string   `json:"internal_name,omitempty"`
	PluginEntryName              *string   `json:"plugin_entry_name,omitempty"`
	Uuid                         *string   `json:"uuid,omitempty"`
	ProblemDir                   *string   `json:"problem_dir,omitempty"`
	TestDir                      *string   `json:"test_dir,omitempty"`
	TestSfx                      *string   `json:"test_sfx,omitempty"`
	CorrDir                      *string   `json:"corr_dir,omitempty"`
	CorrSfx                      *string   `json:"corr_sfx,omitempty"`
	InfoDir                      *string   `json:"info_dir,omitempty"`
	InfoSfx                      *string   `json:"info_sfx,omitempty"`
	TgzDir                       *string   `json:"tgz_dir,omitempty"`
	TgzSfx                       *string   `json:"tgz_sfx,omitempty"`
	TgzdirSfx                    *string   `json:"tgzdir_sfx,omitempty"`
	InputFile                    *string   `json:"input_file,omitempty"`
	OutputFile                   *string   `json:"output_file,omitempty"`
	TestScoreList                *string   `json:"test_score_list,omitempty"`
	Tokens                       *string   `json:"tokens,omitempty"`
	Umask                        *string   `json:"umask,omitempty"`
	OkStatus                     *string   `json:"ok_status,omitempty"`
	HeaderPat                    *string   `json:"header_pat,omitempty"`
	FooterPat                    *string   `json:"footer_pat,omitempty"`
	CompilerEnvPat               *string   `json:"compiler_env_pat,omitempty"`
	ContainerOptions             *string   `json:"container_options,omitempty"`
	ScoreTests                   *string   `json:"score_tests,omitempty"`
	StandardChecker              *string   `json:"standard_checker,omitempty"`
	Spelling                     *string   `json:"spelling,omitempty"`
	StatementFile                *string   `json:"statement_file,omitempty"`
	AlternativesFile             *string   `json:"alternatives_file,omitempty"`
	PluginFile                   *string   `json:"plugin_file,omitempty"`
	XmlFile                      *string   `json:"xml_file,omitempty"`
	StandAttr                    *string   `json:"stand_attr,omitempty"`
	SourceHeader                 *string   `json:"source_header,omitempty"`
	SourceFooter                 *string   `json:"source_footer,omitempty"`
	InteractorTimeLimit          *int32    `json:"interactor_time_limit,omitempty"`
	InteractorRealTimeLimit      *int32    `json:"interactor_real_time_limit,omitempty"`
	CustomCompileCmd             *string   `json:"custom_compile_cmd,omitempty"`
	CustomLangName               *string   `json:"custom_lang_name,omitempty"`
	ExtraSrcDir                  *string   `json:"extra_src_dir,omitempty"`
	StandardValuer               *string   `json:"standard_valuer,omitempty"`
	MdFile                       *string   `json:"md_file,omitempty"`
	TestPat                      *string   `json:"test_pat,omitempty"`
	CorrPat                      *string   `json:"corr_pat,omitempty"`
	InfoPat                      *string   `json:"info_pat,omitempty"`
	TgzPat                       *string   `json:"tgz_pat,omitempty"`
	TgzdirPat                    *string   `json:"tgzdir_pat,omitempty"`
	TestSets                     *[]string `json:"test_sets,omitempty"`
	Normalization                *string   `json:"normalization,omitempty"`
	SrcNormalization             *string   `json:"src_normalization,omitempty"`
	Deadline                     *int64    `json:"deadline,omitempty"`
	StartDate                    *int64    `json:"start_date,omitempty"`
	DatePenalty                  *[]string `json:"date_penalty,omitempty"`
	GroupStartDate               *[]string `json:"group_start_date,omitempty"`
	GroupDeadline                *[]string `json:"group_deadline,omitempty"`
	DisableLanguage              *[]string `json:"disable_language,omitempty"`
	EnableLanguage               *[]string `json:"enable_language,omitempty"`
	Require                      *[]string `json:"require,omitempty"`
	ProvideOk                    *[]string `json:"provide_ok,omitempty"`
	AllowIp                      *[]string `json:"allow_ip,omitempty"`
	LangCompilerEnv              *[]string `json:"lang_compiler_env,omitempty"`
	LangCompilerContainerOptions *[]string `json:"lang_compiler_container_options,omitempty"`
	CheckerEnv                   *[]string `json:"checker_env,omitempty"`
	ValuerEnv                    *[]string `json:"valuer_env,omitempty"`
	InteractorEnv                *[]string `json:"interactor_env,omitempty"`
	StyleCheckerEnv              *[]string `json:"style_checker_env,omitempty"`
	TestCheckerEnv               *[]string `json:"test_checker_env,omitempty"`
	TestGeneratorEnv             *[]string `json:"test_generator_env,omitempty"`
	InitEnv                      *[]string `json:"init_env,omitempty"`
	StartEnv                     *[]string `json:"start_env,omitempty"`
	CheckCmd                     *string   `json:"check_cmd,omitempty"`
	ValuerCmd                    *string   `json:"valuer_cmd,omitempty"`
	InteractorCmd                *string   `json:"interactor_cmd,omitempty"`
	StyleCheckerCmd              *string   `json:"style_checker_cmd,omitempty"`
	TestCheckerCmd               *string   `json:"test_checker_cmd,omitempty"`
	TestGeneratorCmd             *string   `json:"test_generator_cmd,omitempty"`
	InitCmd                      *string   `json:"init_cmd,omitempty"`
	StartCmd                     *string   `json:"start_cmd,omitempty"`
	SolutionSrc                  *string   `json:"solution_src,omitempty"`
	SolutionCmd                  *string   `json:"solution_cmd,omitempty"`
	PostPullCmd                  *string   `json:"post_pull_cmd,omitempty"`
	VcsCompileCmd                *string   `json:"vcs_compile_cmd,omitempty"`
	LangTimeAdj                  *[]string `json:"lang_time_adj,omitempty"`
	LangTimeAdjMillis            *[]string `json:"lang_time_adj_millis,omitempty"`
	SuperRunDir                  *string   `json:"super_run_dir,omitempty"`
	LangMaxVmSize                *[]string `json:"lang_max_vm_size,omitempty"`
	LangMaxStackSize             *[]string `json:"lang_max_stack_size,omitempty"`
	LangMaxRssSize               *[]string `json:"lang_max_rss_size,omitempty"`
	CheckerExtraFiles            *[]string `json:"checker_extra_files,omitempty"`
	StatementEnv                 *[]string `json:"statement_env,omitempty"`
	Alternative                  *[]string `json:"alternative,omitempty"`
	PersonalDeadline             *[]string `json:"personal_deadline,omitempty"`
	ScoreBonus                   *string   `json:"score_bonus,omitempty"`
	OpenTests                    *string   `json:"open_tests,omitempty"`
	FinalOpenTests               *string   `json:"final_open_tests,omitempty"`
	TokenOpenTests               *string   `json:"token_open_tests,omitempty"`
	MaxVmSize                    *int64    `json:"max_vm_size,omitempty"`
	MaxDataSize                  *int64    `json:"max_data_size,omitempty"`
	MaxStackSize                 *int64    `json:"max_stack_size,omitempty"`
	MaxRssSize                   *int64    `json:"max_rss_size,omitempty"`
	MaxCoreSize                  *int64    `json:"max_core_size,omitempty"`
	MaxFileSize                  *int64    `json:"max_file_size,omitempty"`
	CheckerMaxVmSize             *int64    `json:"checker_max_vm_size,omitempty"`
	CheckerMaxStackSize          *int64    `json:"checker_max_stack_size,omitempty"`
	CheckerMaxRssSize            *int64    `json:"checker_max_rss_size,omitempty"`
	MaxOpenFileCount             *int32    `json:"max_open_file_count,omitempty"`
	MaxProcessCount              *int32    `json:"max_process_count,omitempty"`
	ForcedTestCount              *int32    `json:"forced_test_count,omitempty"`
	Extid                        *string   `json:"extid,omitempty"`
	ScoreView                    *[]string `json:"score_view,omitempty"`
}

type Tester struct {
	Id                     int32     `json:"id,omitempty"`
	Name                   string    `json:"name,omitempty"`
	Problem                int32     `json:"problem,omitempty"`
	ProblemName            string    `json:"problem_name,omitempty"`
	Any                    bool      `json:"any,omitempty"`
	IsDos                  *bool     `json:"is_dos,omitempty"`
	NoRedirect             *bool     `json:"no_redirect,omitempty"`
	PriorityAdjustment     *int32    `json:"priority_adjustment,omitempty"`
	IgnoreStderr           *bool     `json:"ignore_stderr,omitempty"`
	Arch                   string    `json:"arch,omitempty"`
	Key                    *string   `json:"key,omitempty"`
	MemoryLimitType        string    `json:"memory_limit_type,omitempty"`
	SecureExecType         string    `json:"secure_exec_type,omitempty"`
	Abstract               bool      `json:"abstract,omitempty"`
	Super                  []string  `json:"super,omitempty"`
	SkipTesting            *bool     `json:"skip_testing,omitempty"`
	NoCoreDump             *bool     `json:"no_core_dump,omitempty"`
	EnableMemoryLimitError *bool     `json:"enable_memory_limit_error,omitempty"`
	KillSignal             *string   `json:"kill_signal,omitempty"`
	MaxStackSize           *int64    `json:"max_stack_size,omitempty"`
	MaxDataSize            *int64    `json:"max_data_size,omitempty"`
	MaxVmSize              *int64    `json:"max_vm_size,omitempty"`
	MaxRssSize             *int64    `json:"max_rss_size,omitempty"`
	ClearEnv               *bool     `json:"clear_env,omitempty"`
	TimeLimitAdjustment    *int32    `json:"time_limit_adjustment,omitempty"`
	TimeLimitAdjMillis     *int32    `json:"time_limit_adj_millis,omitempty"`
	EnableEjudgeEnv        *bool     `json:"enable_ejudge_env,omitempty"`
	RunDir                 string    `json:"run_dir,omitempty"`
	RunQueueDir            string    `json:"run_queue_dir,omitempty"`
	RunExeDir              string    `json:"run_exe_dir,omitempty"`
	RunOutDir              string    `json:"run_out_dir,omitempty"`
	RunStatusDir           string    `json:"run_status_dir,omitempty"`
	RunReportDir           string    `json:"run_report_dir,omitempty"`
	RunTeamReportDir       string    `json:"run_team_report_dir,omitempty"`
	RunFullArchiveDir      string    `json:"run_full_archive_dir,omitempty"`
	CheckDir               string    `json:"check_dir,omitempty"`
	ErrorcodeFile          *string   `json:"errorcode_file,omitempty"`
	ErrorFile              *string   `json:"error_file,omitempty"`
	PrepareCmd             *string   `json:"prepare_cmd,omitempty"`
	StartCmd               *string   `json:"start_cmd,omitempty"`
	NwrunSpoolDir          string    `json:"nwrun_spool_dir,omitempty"`
	StartEnv               *[]string `json:"start_env,omitempty"`
}
